using Dapper;
using System.Collections.Generic;
using System.Threading.Tasks;
using WillBoard.Core.Entities;
using WillBoard.Core.Interfaces.Repositories;

namespace WillBoard.Infrastructure.Repositories.MySql
{
    public class BoardRepository : IBoardRepository
    {
        private readonly ISqlConnectionService _sqlConnectionService;

        public BoardRepository(ISqlConnectionService sqlConnectionService)
        {
            _sqlConnectionService = sqlConnectionService;
        }

        public async Task CreateAsync(Board board)
        {
            using (var dbConnection = _sqlConnectionService.Connection)
            {
                var sql = @"INSERT INTO `Board` (
                                `BoardId`,
                                `Name`,
                                `Availability`,
                                `Type`,
                                `TypeGroupCollection`,
                                `Accessibility`,
                                `AccessibilityPassword`,
                                `AccessibilityIpVersion4NumberCollection`,
                                `AccessibilityIpVersion6NumberCollection`,
                                `Visibility`,
                                `Anonymous`,
                                `Language`,
                                `TimeZone`,
                                `OnlineCounterAvailability`,
                                `CssThemeCollection`,
                                `CssInline`,
                                `CssExternalCollection`,
                                `JsInline`,
                                `JsExternalCollection`,
                                `InformationAside`,
                                `InformationHeader`,
                                `InformationFooter`,
                                `MarkupStaticCustomCollection`,
                                `MarkupDynamicCustomCollection`,
                                `UserIdRequirement`,
                                `CountryRequirement`,
                                `PageMax`,
                                `PageThreadMax`,
                                `PostAvailability`,
                                `ThreadReplyPreviewMax`,
                                `ThreadPinReplyPreviewMax`,
                                `ThreadBumpLockReplyMax`,
                                `ThreadBumpLockTimeMax`,
                                `ThreadExcessiveTimeMax`,
                                `ReplyFieldNameAvailability`,
                                `ReplyFieldNameRequirement`,
                                `ReplyFieldNameLengthMin`,
                                `ReplyFieldNameLengthMax`,
                                `ThreadFieldNameAvailability`,
                                `ThreadFieldNameRequirement`,
                                `ThreadFieldNameLengthMin`,
                                `ThreadFieldNameLengthMax`,
                                `ReplyFieldEmailAvailability`,
                                `ReplyFieldEmailRequirement`,
                                `ReplyFieldEmailLengthMin`,
                                `ReplyFieldEmailLengthMax`,
                                `ThreadFieldEmailAvailability`,
                                `ThreadFieldEmailRequirement`,
                                `ThreadFieldEmailLengthMin`,
                                `ThreadFieldEmailLengthMax`,
                                `ReplyFieldSubjectAvailability`,
                                `ReplyFieldSubjectRequirement`,
                                `ReplyFieldSubjectLengthMin`,
                                `ReplyFieldSubjectLengthMax`,
                                `ThreadFieldSubjectAvailability`,
                                `ThreadFieldSubjectRequirement`,
                                `ThreadFieldSubjectLengthMin`,
                                `ThreadFieldSubjectLengthMax`,
                                `ReplyFieldMessageAvailability`,
                                `ReplyFieldMessageRequirement`,
                                `ReplyFieldMessageLengthMin`,
                                `ReplyFieldMessageLengthMax`,
                                `ReplyFieldMessageLineMax`,
                                `ReplyFieldMessageLinkMax`,
                                `ReplyFieldMessageMentionMax`,
                                `ThreadFieldMessageAvailability`,
                                `ThreadFieldMessageRequirement`,
                                `ThreadFieldMessageLengthMin`,
                                `ThreadFieldMessageLengthMax`,
                                `ThreadFieldMessageLineMax`,
                                `ThreadFieldMessageLinkMax`,
                                `ThreadFieldMessageMentionMax`,
                                `ReplyFieldFileAvailability`,
                                `ReplyFieldFileRequirement`,
                                `ReplyFieldFileSizeMin`,
                                `ReplyFieldFileSizeMax`,
                                `ReplyFieldFileOriginality`,
                                `ReplyFieldFileTypeCollection`,
                                `ReplyFieldFileImageWidthMin`,
                                `ReplyFieldFileImageWidthMax`,
                                `ReplyFieldFileImageHeightMin`,
                                `ReplyFieldFileImageHeightMax`,
                                `ReplyFieldFileVideoWidthMin`,
                                `ReplyFieldFileVideoWidthMax`,
                                `ReplyFieldFileVideoHeightMax`,
                                `ReplyFieldFileVideoHeightMin`,
                                `ReplyFieldFileVideoDurationMin`,
                                `ReplyFieldFileVideoDurationMax`,
                                `ReplyFieldFileAudioDurationMin`,
                                `ReplyFieldFileAudioDurationMax`,
                                `ReplyFilePreviewWidthMax`,
                                `ReplyFilePreviewHeightMax`,
                                `ThreadFieldFileAvailability`,
                                `ThreadFieldFileRequirement`,
                                `ThreadFieldFileSizeMin`,
                                `ThreadFieldFileSizeMax`,
                                `ThreadFieldFileOriginality`,
                                `ThreadFieldFileTypeCollection`,
                                `ThreadFieldFileImageWidthMin`,
                                `ThreadFieldFileImageWidthMax`,
                                `ThreadFieldFileImageHeightMin`,
                                `ThreadFieldFileImageHeightMax`,
                                `ThreadFieldFileVideoWidthMin`,
                                `ThreadFieldFileVideoWidthMax`,
                                `ThreadFieldFileVideoHeightMax`,
                                `ThreadFieldFileVideoHeightMin`,
                                `ThreadFieldFileVideoDurationMin`,
                                `ThreadFieldFileVideoDurationMax`,
                                `ThreadFieldFileAudioDurationMin`,
                                `ThreadFieldFileAudioDurationMax`,
                                `ThreadFilePreviewWidthMax`,
                                `ThreadFilePreviewHeightMax`,
                                `ThreadFieldOptionSpoilerAvailability`,
                                `ThreadFieldOptionSageAvailability`,
                                `ThreadFieldOptionUserIdAvailability`,
                                `ThreadFieldOptionCountryAvailability`,
                                `ReplyFieldOptionSpoilerAvailability`,
                                `ReplyFieldOptionSageAvailability`,
                                `ReplyFieldPasswordAvailability`,
                                `ReplyFieldPasswordRequirement`,
                                `ReplyFieldPasswordLengthMin`,
                                `ReplyFieldPasswordLengthMax`,
                                `ThreadFieldPasswordAvailability`,
                                `ThreadFieldPasswordRequirement`,
                                `ThreadFieldPasswordLengthMin`,
                                `ThreadFieldPasswordLengthMax`,
                                `ReplyTimeMin`,
                                `ThreadTimeMin`,
                                `ReplyDeleteAvailability`,
                                `ReplyDeleteTimeMin`,
                                `ReplyDeleteTimeMax`,
                                `ThreadDeleteAvailability`,
                                `ThreadDeleteTimeMin`,
                                `ThreadDeleteTimeMax`,
                                `ReplyFileDeleteAvailability`,
                                `ReplyFileDeleteTimeMin`,
                                `ReplyFileDeleteTimeMax`,
                                `ThreadFileDeleteAvailability`,
                                `ThreadFileDeleteTimeMin`,
                                `ThreadFileDeleteTimeMax`,
                                `ReportBoardAvailability`,
                                `ReportBoardLengthMin`,
                                `ReportBoardLengthMax`,
                                `ReportBoardIpMax`,
                                `ReportBoardTimeMin`,
                                `CountryIpVersion4BlockAvailability`,
                                `CountryIpVersion4BlockCollection`,
                                `CountryIpVersion4ExclusionIpNumberCollection`,
                                `CountryIpVersion6BlockAvailability`,
                                `CountryIpVersion6BlockCollection`,
                                `CountryIpVersion6ExclusionIpNumberCollection`,
                                `BadIpVersion4BlockAvailability`,
                                `BadIpVersion4BlockExclusionIpNumberCollection`,
                                `BadIpVersion6BlockAvailability`,
                                `BadIpVersion6BlockExclusionIpNumberCollection`,
                                `DnsBlockListIpVersion4Availability`,
                                `DnsBlockListIpVersion4Cache`,
                                `DnsBlockListIpVersion4Collection`,
                                `DnsBlockListIpVersion4ExclusionIpNumberCollection`,
                                `DnsBlockListIpVersion6Availability`,
                                `DnsBlockListIpVersion6Cache`,
                                `DnsBlockListIpVersion6Collection`,
                                `DnsBlockListIpVersion6ExclusionIpNumberCollection`,
                                `ApiBlockListIpVersion4Availability`,
                                `ApiBlockListIpVersion4Cache`,
                                `ApiBlockListIpVersion4Collection`,
                                `ApiBlockListIpVersion4ExclusionIpNumberCollection`,
                                `ApiBlockListIpVersion6Availability`,
                                `ApiBlockListIpVersion6Cache`,
                                `ApiBlockListIpVersion6Collection`,
                                `ApiBlockListIpVersion6ExclusionIpNumberCollection`,
                                `FieldVerificationType`,
                                `VerificationPublicKey`,
                                `VerificationSecretKey`,
                                `ReplyFieldVerificationMode`,
                                `ReplyFieldVerificationLocalTime`,
                                `ThreadFieldVerificationMode`,
                                `ThreadFieldVerificationLocalTime`,
                                `SynchronizationThreadAvailability`,
                                `SynchronizationBoardAvailability`,
                                `SearchAvailability`,
                                `CatalogAvailability`,
                                `AnonymizationAvailability`,
                                `AnonymizationTimeMax`
                                ) VALUES (
                                @BoardId,
                                @Name,
                                @Availability,
                                @Type,
                                @TypeGroupCollection,
                                @Accessibility,
                                @AccessibilityPassword,
                                @AccessibilityIpVersion4NumberCollection,
                                @AccessibilityIpVersion6NumberCollection,
                                @Visibility,
                                @Anonymous,
                                @Language,
                                @TimeZone,
                                @OnlineCounterAvailability,
                                @CssThemeCollection,
                                @CssInline,
                                @CssExternalCollection,
                                @JsInline,
                                @JsExternalCollection,
                                @InformationAside,
                                @InformationHeader,
                                @InformationFooter,
                                @MarkupStaticCustomCollection,
                                @MarkupDynamicCustomCollection,
                                @UserIdRequirement,
                                @CountryRequirement,
                                @PageMax,
                                @PageThreadMax,
                                @PostAvailability,
                                @ThreadReplyPreviewMax,
                                @ThreadPinReplyPreviewMax,
                                @ThreadBumpLockReplyMax,
                                @ThreadBumpLockTimeMax,
                                @ThreadExcessiveTimeMax,
                                @ReplyFieldNameAvailability,
                                @ReplyFieldNameRequirement,
                                @ReplyFieldNameLengthMin,
                                @ReplyFieldNameLengthMax,
                                @ThreadFieldNameAvailability,
                                @ThreadFieldNameRequirement,
                                @ThreadFieldNameLengthMin,
                                @ThreadFieldNameLengthMax,
                                @ReplyFieldEmailAvailability,
                                @ReplyFieldEmailRequirement,
                                @ReplyFieldEmailLengthMin,
                                @ReplyFieldEmailLengthMax,
                                @ThreadFieldEmailAvailability,
                                @ThreadFieldEmailRequirement,
                                @ThreadFieldEmailLengthMin,
                                @ThreadFieldEmailLengthMax,
                                @ReplyFieldSubjectAvailability,
                                @ReplyFieldSubjectRequirement,
                                @ReplyFieldSubjectLengthMin,
                                @ReplyFieldSubjectLengthMax,
                                @ThreadFieldSubjectAvailability,
                                @ThreadFieldSubjectRequirement,
                                @ThreadFieldSubjectLengthMin,
                                @ThreadFieldSubjectLengthMax,
                                @ReplyFieldMessageAvailability,
                                @ReplyFieldMessageRequirement,
                                @ReplyFieldMessageLengthMin,
                                @ReplyFieldMessageLengthMax,
                                @ReplyFieldMessageLineMax,
                                @ReplyFieldMessageLinkMax,
                                @ReplyFieldMessageMentionMax,
                                @ThreadFieldMessageAvailability,
                                @ThreadFieldMessageRequirement,
                                @ThreadFieldMessageLengthMin,
                                @ThreadFieldMessageLengthMax,
                                @ThreadFieldMessageLineMax,
                                @ThreadFieldMessageLinkMax,
                                @ThreadFieldMessageMentionMax,
                                @ReplyFieldFileAvailability,
                                @ReplyFieldFileRequirement,
                                @ReplyFieldFileSizeMin,
                                @ReplyFieldFileSizeMax,
                                @ReplyFieldFileOriginality,
                                @ReplyFieldFileTypeCollection,
                                @ReplyFieldFileImageWidthMin,
                                @ReplyFieldFileImageWidthMax,
                                @ReplyFieldFileImageHeightMin,
                                @ReplyFieldFileImageHeightMax,
                                @ReplyFieldFileVideoWidthMin,
                                @ReplyFieldFileVideoWidthMax,
                                @ReplyFieldFileVideoHeightMax,
                                @ReplyFieldFileVideoHeightMin,
                                @ReplyFieldFileVideoDurationMin,
                                @ReplyFieldFileVideoDurationMax,
                                @ReplyFieldFileAudioDurationMin,
                                @ReplyFieldFileAudioDurationMax,
                                @ReplyFilePreviewWidthMax,
                                @ReplyFilePreviewHeightMax,
                                @ThreadFieldFileAvailability,
                                @ThreadFieldFileRequirement,
                                @ThreadFieldFileSizeMin,
                                @ThreadFieldFileSizeMax,
                                @ThreadFieldFileOriginality,
                                @ThreadFieldFileTypeCollection,
                                @ThreadFieldFileImageWidthMin,
                                @ThreadFieldFileImageWidthMax,
                                @ThreadFieldFileImageHeightMin,
                                @ThreadFieldFileImageHeightMax,
                                @ThreadFieldFileVideoWidthMin,
                                @ThreadFieldFileVideoWidthMax,
                                @ThreadFieldFileVideoHeightMax,
                                @ThreadFieldFileVideoHeightMin,
                                @ThreadFieldFileVideoDurationMin,
                                @ThreadFieldFileVideoDurationMax,
                                @ThreadFieldFileAudioDurationMin,
                                @ThreadFieldFileAudioDurationMax,
                                @ThreadFilePreviewWidthMax,
                                @ThreadFilePreviewHeightMax,
                                @ThreadFieldOptionSpoilerAvailability,
                                @ThreadFieldOptionSageAvailability,
                                @ThreadFieldOptionUserIdAvailability,
                                @ThreadFieldOptionCountryAvailability,
                                @ReplyFieldOptionSpoilerAvailability,
                                @ReplyFieldOptionSageAvailability,
                                @ReplyFieldPasswordAvailability,
                                @ReplyFieldPasswordRequirement,
                                @ReplyFieldPasswordLengthMin,
                                @ReplyFieldPasswordLengthMax,
                                @ThreadFieldPasswordAvailability,
                                @ThreadFieldPasswordRequirement,
                                @ThreadFieldPasswordLengthMin,
                                @ThreadFieldPasswordLengthMax,
                                @ReplyTimeMin,
                                @ThreadTimeMin,
                                @ReplyDeleteAvailability,
                                @ReplyDeleteTimeMin,
                                @ReplyDeleteTimeMax,
                                @ThreadDeleteAvailability,
                                @ThreadDeleteTimeMin,
                                @ThreadDeleteTimeMax,
                                @ReplyFileDeleteAvailability,
                                @ReplyFileDeleteTimeMin,
                                @ReplyFileDeleteTimeMax,
                                @ThreadFileDeleteAvailability,
                                @ThreadFileDeleteTimeMin,
                                @ThreadFileDeleteTimeMax,
                                @ReportBoardAvailability,
                                @ReportBoardLengthMin,
                                @ReportBoardLengthMax,
                                @ReportBoardIpMax,
                                @ReportBoardTimeMin,
                                @CountryIpVersion4BlockAvailability,
                                @CountryIpVersion4BlockCollection,
                                @CountryIpVersion4ExclusionIpNumberCollection,
                                @CountryIpVersion6BlockAvailability,
                                @CountryIpVersion6BlockCollection,
                                @CountryIpVersion6ExclusionIpNumberCollection,
                                @BadIpVersion4BlockAvailability,
                                @BadIpVersion4BlockExclusionIpNumberCollection,
                                @BadIpVersion6BlockAvailability,
                                @BadIpVersion6BlockExclusionIpNumberCollection,
                                @DnsBlockListIpVersion4Availability,
                                @DnsBlockListIpVersion4Cache,
                                @DnsBlockListIpVersion4Collection,
                                @DnsBlockListIpVersion4ExclusionIpNumberCollection,
                                @DnsBlockListIpVersion6Availability,
                                @DnsBlockListIpVersion6Cache,
                                @DnsBlockListIpVersion6Collection,
                                @DnsBlockListIpVersion6ExclusionIpNumberCollection,
                                @ApiBlockListIpVersion4Availability,
                                @ApiBlockListIpVersion4Cache,
                                @ApiBlockListIpVersion4Collection,
                                @ApiBlockListIpVersion4ExclusionIpNumberCollection,
                                @ApiBlockListIpVersion6Availability,
                                @ApiBlockListIpVersion6Cache,
                                @ApiBlockListIpVersion6Collection,
                                @ApiBlockListIpVersion6ExclusionIpNumberCollection,
                                @FieldVerificationType,
                                @VerificationPublicKey,
                                @VerificationSecretKey,
                                @ReplyFieldVerificationMode,
                                @ReplyFieldVerificationLocalTime,
                                @ThreadFieldVerificationMode,
                                @ThreadFieldVerificationLocalTime,
                                @SynchronizationThreadAvailability,
                                @SynchronizationBoardAvailability,
                                @SearchAvailability,
                                @CatalogAvailability,
                                @AnonymizationAvailability,
                                @AnonymizationTimeMax);";

                dbConnection.Open();
                await dbConnection.ExecuteAsync(sql, board);
            }
        }

        public async Task<IEnumerable<Board>> ReadCollectionAsync()
        {
            using (var dbConnection = _sqlConnectionService.Connection)
            {
                var sql = "SELECT * FROM `Board` ORDER BY `BoardId` ASC;";

                dbConnection.Open();
                return await dbConnection.QueryAsync<Board>(sql);
            }
        }

        public async Task UpdateAsync(Board board)
        {
            using (var dbConnection = _sqlConnectionService.Connection)
            {
                var sql = @"UPDATE `Board` SET
                                `Name` = @Name,
                                `Availability` = @Availability,
                                `Type` = @Type,
                                `TypeGroupCollection` = @TypeGroupCollection,
                                `Accessibility` = @Accessibility,
                                `AccessibilityPassword` = @AccessibilityPassword,
                                `AccessibilityIpVersion4NumberCollection` = @AccessibilityIpVersion4NumberCollection,
                                `AccessibilityIpVersion6NumberCollection` = @AccessibilityIpVersion6NumberCollection,
                                `Visibility` = @Visibility,
                                `Anonymous` = @Anonymous,
                                `Language` = @Language,
                                `TimeZone` = @TimeZone,
                                `OnlineCounterAvailability` = @OnlineCounterAvailability,
                                `CssThemeCollection` = @CssThemeCollection,
                                `CssInline` = @CssInline,
                                `CssExternalCollection` = @CssExternalCollection,
                                `JsInline` = @JsInline,
                                `JsExternalCollection` = @JsExternalCollection,
                                `InformationAside` = @InformationAside,
                                `InformationHeader` = @InformationHeader,
                                `InformationFooter` = @InformationFooter,
                                `MarkupStaticCustomCollection` = @MarkupStaticCustomCollection,
                                `MarkupDynamicCustomCollection` = @MarkupDynamicCustomCollection,
                                `UserIdRequirement` = @UserIdRequirement,
                                `CountryRequirement` = @CountryRequirement,
                                `PageMax` = @PageMax,
                                `PageThreadMax` = @PageThreadMax,
                                `PostAvailability` = @PostAvailability,
                                `ThreadReplyPreviewMax` = @ThreadReplyPreviewMax,
                                `ThreadPinReplyPreviewMax` = @ThreadPinReplyPreviewMax,
                                `ThreadBumpLockReplyMax` = @ThreadBumpLockReplyMax,
                                `ThreadBumpLockTimeMax` = @ThreadBumpLockTimeMax,
                                `ThreadExcessiveTimeMax` = @ThreadExcessiveTimeMax,
                                `ReplyFieldNameAvailability` = @ReplyFieldNameAvailability,
                                `ReplyFieldNameRequirement` = @ReplyFieldNameRequirement,
                                `ReplyFieldNameLengthMin` = @ReplyFieldNameLengthMin,
                                `ReplyFieldNameLengthMax` = @ReplyFieldNameLengthMax,
                                `ThreadFieldNameAvailability` = @ThreadFieldNameAvailability,
                                `ThreadFieldNameRequirement` = @ThreadFieldNameRequirement,
                                `ThreadFieldNameLengthMin` = @ThreadFieldNameLengthMin,
                                `ThreadFieldNameLengthMax` = @ThreadFieldNameLengthMax,
                                `ReplyFieldEmailAvailability` = @ReplyFieldEmailAvailability,
                                `ReplyFieldEmailRequirement` = @ReplyFieldEmailRequirement,
                                `ReplyFieldEmailLengthMin` = @ReplyFieldEmailLengthMin,
                                `ReplyFieldEmailLengthMax` = @ReplyFieldEmailLengthMax,
                                `ThreadFieldEmailAvailability` = @ThreadFieldEmailAvailability,
                                `ThreadFieldEmailRequirement` = @ThreadFieldEmailRequirement,
                                `ThreadFieldEmailLengthMin` = @ThreadFieldEmailLengthMin,
                                `ThreadFieldEmailLengthMax` = @ThreadFieldEmailLengthMax,
                                `ReplyFieldSubjectAvailability` = @ReplyFieldSubjectAvailability,
                                `ReplyFieldSubjectRequirement` = @ReplyFieldSubjectRequirement,
                                `ReplyFieldSubjectLengthMin` = @ReplyFieldSubjectLengthMin,
                                `ReplyFieldSubjectLengthMax` = @ReplyFieldSubjectLengthMax,
                                `ThreadFieldSubjectAvailability` = @ThreadFieldSubjectAvailability,
                                `ThreadFieldSubjectRequirement` = @ThreadFieldSubjectRequirement,
                                `ThreadFieldSubjectLengthMin` = @ThreadFieldSubjectLengthMin,
                                `ThreadFieldSubjectLengthMax` = @ThreadFieldSubjectLengthMax,
                                `ReplyFieldMessageAvailability` = @ReplyFieldMessageAvailability,
                                `ReplyFieldMessageRequirement` = @ReplyFieldMessageRequirement,
                                `ReplyFieldMessageLengthMin` = @ReplyFieldMessageLengthMin,
                                `ReplyFieldMessageLengthMax` = @ReplyFieldMessageLengthMax,
                                `ReplyFieldMessageLineMax` = @ReplyFieldMessageLineMax,
                                `ReplyFieldMessageLinkMax` = @ReplyFieldMessageLinkMax,
                                `ReplyFieldMessageMentionMax` = @ReplyFieldMessageMentionMax,
                                `ThreadFieldMessageAvailability` = @ThreadFieldMessageAvailability,
                                `ThreadFieldMessageRequirement` = @ThreadFieldMessageRequirement,
                                `ThreadFieldMessageLengthMin` = @ThreadFieldMessageLengthMin,
                                `ThreadFieldMessageLengthMax` = @ThreadFieldMessageLengthMax,
                                `ThreadFieldMessageLineMax` = @ThreadFieldMessageLineMax,
                                `ThreadFieldMessageLinkMax` = @ThreadFieldMessageLinkMax,
                                `ThreadFieldMessageMentionMax` = @ThreadFieldMessageMentionMax,
                                `ReplyFieldFileAvailability` = @ReplyFieldFileAvailability,
                                `ReplyFieldFileRequirement` = @ReplyFieldFileRequirement,
                                `ReplyFieldFileSizeMin` = @ReplyFieldFileSizeMin,
                                `ReplyFieldFileSizeMax` = @ReplyFieldFileSizeMax,
                                `ReplyFieldFileOriginality` = @ReplyFieldFileOriginality,
                                `ReplyFieldFileTypeCollection` = @ReplyFieldFileTypeCollection,
                                `ReplyFieldFileImageWidthMin` = @ReplyFieldFileImageWidthMin,
                                `ReplyFieldFileImageWidthMax` = @ReplyFieldFileImageWidthMax,
                                `ReplyFieldFileImageHeightMin` = @ReplyFieldFileImageHeightMin,
                                `ReplyFieldFileImageHeightMax` = @ReplyFieldFileImageHeightMax,
                                `ReplyFieldFileVideoWidthMin` = @ReplyFieldFileVideoWidthMin,
                                `ReplyFieldFileVideoWidthMax` = @ReplyFieldFileVideoWidthMax,
                                `ReplyFieldFileVideoHeightMax` = @ReplyFieldFileVideoHeightMax,
                                `ReplyFieldFileVideoHeightMin` = @ReplyFieldFileVideoHeightMin,
                                `ReplyFieldFileVideoDurationMin` = @ReplyFieldFileVideoDurationMin,
                                `ReplyFieldFileVideoDurationMax` = @ReplyFieldFileVideoDurationMax,
                                `ReplyFieldFileAudioDurationMin` = @ReplyFieldFileAudioDurationMin,
                                `ReplyFieldFileAudioDurationMax` = @ReplyFieldFileAudioDurationMax,
                                `ReplyFilePreviewWidthMax` = @ReplyFilePreviewWidthMax,
                                `ReplyFilePreviewHeightMax` = @ReplyFilePreviewHeightMax,
                                `ThreadFieldFileAvailability` = @ThreadFieldFileAvailability,
                                `ThreadFieldFileRequirement` = @ThreadFieldFileRequirement,
                                `ThreadFieldFileSizeMin` = @ThreadFieldFileSizeMin,
                                `ThreadFieldFileSizeMax` = @ThreadFieldFileSizeMax,
                                `ThreadFieldFileOriginality` = @ThreadFieldFileOriginality,
                                `ThreadFieldFileTypeCollection` = @ThreadFieldFileTypeCollection,
                                `ThreadFieldFileImageWidthMin` = @ThreadFieldFileImageWidthMin,
                                `ThreadFieldFileImageWidthMax` = @ThreadFieldFileImageWidthMax,
                                `ThreadFieldFileImageHeightMin` = @ThreadFieldFileImageHeightMin,
                                `ThreadFieldFileImageHeightMax` = @ThreadFieldFileImageHeightMax,
                                `ThreadFieldFileVideoWidthMin` = @ThreadFieldFileVideoWidthMin,
                                `ThreadFieldFileVideoWidthMax` = @ThreadFieldFileVideoWidthMax,
                                `ThreadFieldFileVideoHeightMax` = @ThreadFieldFileVideoHeightMax,
                                `ThreadFieldFileVideoHeightMin` = @ThreadFieldFileVideoHeightMin,
                                `ThreadFieldFileVideoDurationMin` = @ThreadFieldFileVideoDurationMin,
                                `ThreadFieldFileVideoDurationMax` = @ThreadFieldFileVideoDurationMax,
                                `ThreadFieldFileAudioDurationMin` = @ThreadFieldFileAudioDurationMin,
                                `ThreadFieldFileAudioDurationMax` = @ThreadFieldFileAudioDurationMax,
                                `ThreadFilePreviewWidthMax` = @ThreadFilePreviewWidthMax,
                                `ThreadFilePreviewHeightMax` = @ThreadFilePreviewHeightMax,
                                `ThreadFieldOptionSpoilerAvailability` = @ThreadFieldOptionSpoilerAvailability,
                                `ThreadFieldOptionSageAvailability` = @ThreadFieldOptionSageAvailability,
                                `ThreadFieldOptionUserIdAvailability` = @ThreadFieldOptionUserIdAvailability,
                                `ThreadFieldOptionCountryAvailability` = @ThreadFieldOptionCountryAvailability,
                                `ReplyFieldOptionSpoilerAvailability` = @ReplyFieldOptionSpoilerAvailability,
                                `ReplyFieldOptionSageAvailability` = @ReplyFieldOptionSageAvailability,
                                `ReplyFieldPasswordAvailability` = @ReplyFieldPasswordAvailability,
                                `ReplyFieldPasswordRequirement` = @ReplyFieldPasswordRequirement,
                                `ReplyFieldPasswordLengthMin` = @ReplyFieldPasswordLengthMin,
                                `ReplyFieldPasswordLengthMax` = @ReplyFieldPasswordLengthMax,
                                `ThreadFieldPasswordAvailability` = @ThreadFieldPasswordAvailability,
                                `ThreadFieldPasswordRequirement` = @ThreadFieldPasswordRequirement,
                                `ThreadFieldPasswordLengthMin` = @ThreadFieldPasswordLengthMin,
                                `ThreadFieldPasswordLengthMax` = @ThreadFieldPasswordLengthMax,
                                `ReplyTimeMin` = @ReplyTimeMin,
                                `ThreadTimeMin` = @ThreadTimeMin,
                                `ReplyDeleteAvailability` = @ReplyDeleteAvailability,
                                `ReplyDeleteTimeMin` = @ReplyDeleteTimeMin,
                                `ReplyDeleteTimeMax` = @ReplyDeleteTimeMax,
                                `ThreadDeleteAvailability` = @ThreadDeleteAvailability,
                                `ThreadDeleteTimeMin` = @ThreadDeleteTimeMin,
                                `ThreadDeleteTimeMax` = @ThreadDeleteTimeMax,
                                `ReplyFileDeleteAvailability` = @ReplyFileDeleteAvailability,
                                `ReplyFileDeleteTimeMin` = @ReplyFileDeleteTimeMin,
                                `ReplyFileDeleteTimeMax` = @ReplyFileDeleteTimeMax,
                                `ThreadFileDeleteAvailability` = @ThreadFileDeleteAvailability,
                                `ThreadFileDeleteTimeMin` = @ThreadFileDeleteTimeMin,
                                `ThreadFileDeleteTimeMax` = @ThreadFileDeleteTimeMax,
                                `ReportBoardAvailability` = @ReportBoardAvailability,
                                `ReportBoardLengthMin` = @ReportBoardLengthMin,
                                `ReportBoardLengthMax` = @ReportBoardLengthMax,
                                `ReportBoardIpMax` = @ReportBoardIpMax,
                                `ReportBoardTimeMin` = @ReportBoardTimeMin,
                                `CountryIpVersion4BlockAvailability` = @CountryIpVersion4BlockAvailability,
                                `CountryIpVersion4BlockCollection` = @CountryIpVersion4BlockCollection,
                                `CountryIpVersion4ExclusionIpNumberCollection` = @CountryIpVersion4ExclusionIpNumberCollection,
                                `CountryIpVersion6BlockAvailability` = @CountryIpVersion6BlockAvailability,
                                `CountryIpVersion6BlockCollection` = @CountryIpVersion6BlockCollection,
                                `CountryIpVersion6ExclusionIpNumberCollection` = @CountryIpVersion6ExclusionIpNumberCollection,
                                `BadIpVersion4BlockAvailability` = @BadIpVersion4BlockAvailability,
                                `BadIpVersion4BlockExclusionIpNumberCollection` = @BadIpVersion4BlockExclusionIpNumberCollection,
                                `BadIpVersion6BlockAvailability` = @BadIpVersion6BlockAvailability,
                                `BadIpVersion6BlockExclusionIpNumberCollection` = @BadIpVersion6BlockExclusionIpNumberCollection,
                                `DnsBlockListIpVersion4Availability` = @DnsBlockListIpVersion4Availability,
                                `DnsBlockListIpVersion4Cache` = @DnsBlockListIpVersion4Cache,
                                `DnsBlockListIpVersion4Collection` = @DnsBlockListIpVersion4Collection,
                                `DnsBlockListIpVersion4ExclusionIpNumberCollection` = @DnsBlockListIpVersion4ExclusionIpNumberCollection,
                                `DnsBlockListIpVersion6Availability` = @DnsBlockListIpVersion6Availability,
                                `DnsBlockListIpVersion6Cache` = @DnsBlockListIpVersion6Cache,
                                `DnsBlockListIpVersion6Collection` = @DnsBlockListIpVersion6Collection,
                                `DnsBlockListIpVersion6ExclusionIpNumberCollection` = @DnsBlockListIpVersion6ExclusionIpNumberCollection,
                                `ApiBlockListIpVersion4Availability` = @ApiBlockListIpVersion4Availability,
                                `ApiBlockListIpVersion4Cache` = @ApiBlockListIpVersion4Cache,
                                `ApiBlockListIpVersion4Collection` = @ApiBlockListIpVersion4Collection,
                                `ApiBlockListIpVersion4ExclusionIpNumberCollection` = @ApiBlockListIpVersion4ExclusionIpNumberCollection,
                                `ApiBlockListIpVersion6Availability` = @ApiBlockListIpVersion6Availability,
                                `ApiBlockListIpVersion6Cache` = @ApiBlockListIpVersion6Cache,
                                `ApiBlockListIpVersion6Collection` = @ApiBlockListIpVersion6Collection,
                                `ApiBlockListIpVersion6ExclusionIpNumberCollection` = @ApiBlockListIpVersion6ExclusionIpNumberCollection,
                                `FieldVerificationType` = @FieldVerificationType,
                                `VerificationPublicKey` = @VerificationPublicKey,
                                `VerificationSecretKey` = @VerificationSecretKey,
                                `ReplyFieldVerificationMode` = @ReplyFieldVerificationMode,
                                `ReplyFieldVerificationLocalTime` = @ReplyFieldVerificationLocalTime,
                                `ThreadFieldVerificationMode` = @ThreadFieldVerificationMode,
                                `ThreadFieldVerificationLocalTime` = @ThreadFieldVerificationLocalTime,
                                `SynchronizationThreadAvailability` = @SynchronizationThreadAvailability,
                                `SynchronizationBoardAvailability` = @SynchronizationBoardAvailability,
                                `SearchAvailability` = @SearchAvailability,
                                `CatalogAvailability` = @CatalogAvailability,
                                `AnonymizationAvailability` = @AnonymizationAvailability,
                                `AnonymizationTimeMax` = @AnonymizationTimeMax
                                WHERE `BoardId` = @BoardId;";

                dbConnection.Open();
                await dbConnection.ExecuteAsync(sql, board);
            }
        }

        public async Task DeleteAsync(string boardId)
        {
            using (var dbConnection = _sqlConnectionService.Connection)
            {
                var sql = "DELETE FROM `Board` WHERE `BoardId` = @BoardId;";

                dbConnection.Open();
                await dbConnection.ExecuteAsync(sql, new { BoardId = boardId });
            }
        }
    }
}